name: release-note-action
description: Action to generate release note from commit history

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  base:
    description: Base branch or commit
    required: true
  head:
    description: Head branch or commit
    required: true
  path:
    description: Path to get commit history of subtree
    required: true
    default: '.'

outputs:
  body:
    description: List of commits with associated pull requests (Markdown)
  associated-pull-requests:
    description: List of pull requests associated to commits (Multiline)
  pull-request-list:
    description: List of pull requests in multiline (deprecated)
  pull-request-list-markdown:
    description: List of pull requests in markdown (deprecated)

runs:
  using: 'node16'
  main: 'dist/index.js'
