name: list-associated-pull-requests-action
description: Action to generate a list of associated pull requests by paths in monorepo

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  pull-request:
    description: Pull request to parse (experimental)
    required: false
  base:
    description: Base branch or commit
    required: false
  head:
    description: Head branch or commit
    required: false
  group-by-paths:
    description: Group pull requests by paths (Multiline)
    required: false
  show-others-group:
    description: Show others group
    required: true
    default: 'true'
  max-fetch-commits:
    description: Maximum number of commits to fetch. Default is unlimited
    required: false

outputs:
  body:
    description: List of associated pull requests (Markdown)
  body-groups:
    description: Grouped lists of associated pull requests (Markdown)
  body-others:
    description: Others list of associated pull requests (Markdown)
  json:
    description: List of associated pull requests (JSON)

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: git-pull-request
  color: blue
