name: release-note-action
description: Action to generate release note from commit history

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  pull-request:
    description: Pull request to parse (experimental)
    required: false
  base:
    description: Base branch or commit
    required: false
  head:
    description: Head branch or commit
    required: false
  path:
    description: Path to get commit history of subtree
    required: true
    default: '.'
  group-by-sub-paths:
    description: Group pull requests by sub-paths (Multiline)
    required: false

outputs:
  body:
    description: List of associated pull requests or commits (Markdown)
  associated-pull-requests:
    description: List of associated pull request numbers (Multiline)
  pull-request-list:
    description: List of pull requests in multiline (deprecated)
  pull-request-list-markdown:
    description: List of pull requests in markdown (deprecated)

runs:
  using: 'node16'
  main: 'dist/index.js'
